apiVersion: v1
kind: Service
metadata:
        name: hello-svc-service
spec:
    type: NodePort
    ports:
      - port: 3050
        targetPort: 8080
        nodePort: 31313
    selector:
      app: hello_svc
